name: Create Archive
on:
  push:
    branches:
      - dev
    paths:
      - "GameData"
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Archive Release
        uses: TheDoctor0/zip-release@0.7.6
        with:
          type: "zip"
          filename: "preRelease.zip"
          exclusions: "*.git* /*node_modules/* .editorconfig"
          token: ${{ secrets.GITHUB_TOKEN }}
